arch:
- 1433
- 16
- 8
batch_size: 256
fd_layers:
- 0
features: stack
gyration: true
k: 4
layer_type: !!python/name:torch_geometric.nn.conv.gat_conv.GATConv ''
lr: 0.001
model_name: Cora
ngram: 1
norm: 1.0
num_classes: 7
num_workers: 4
skip: 1
use_fd: false
use_weight: true
